# Generated by Django 5.1.15 on 2026-06-30 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('supplier_code', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['tenant', 'name'], name='suppliers_s_tenant__566edc_idx'), models.Index(fields=['tenant', 'is_active'], name='suppliers_s_tenant__14ad59_idx'), models.Index(fields=['tenant', 'supplier_code'], name='suppliers_s_tenant__e321ad_idx')],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
