# Generated by Django 5.1.15 on 2026-07-15 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_subscription_plans_and_tenant_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_track_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='receipt_business_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='receipt_prefix',
            field=models.CharField(default='POS', max_length=16),
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('completed_steps', models.JSONField(blank=True, default=list)),
                ('skipped_steps', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
