# Generated by Django 5.1.15 on 2026-07-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_default_tax_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_reorder_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='receipt_footer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tax_identification_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vat_registration_number',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
