# Generated by Django 5.1.15 on 2026-06-30 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=150)),
                ('key_prefix', models.CharField(max_length=12, unique=True)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('can_view_cost', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_keys_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_keys', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'label', 'id'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='api_apikey_tenant__ede7b0_idx'), models.Index(fields=['tenant', 'key_prefix'], name='api_apikey_tenant__ddb5b7_idx')],
            },
        ),
    ]
