# Generated by Django 5.1.15 on 2026-06-30 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner_admin', 'Owner/Admin'), ('manager', 'Manager'), ('cashier', 'Cashier')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tenant_id', 'user_id'],
                'indexes': [models.Index(fields=['tenant', 'user'], name='accounts_te_tenant__791d69_idx'), models.Index(fields=['tenant', 'role'], name='accounts_te_tenant__5e1e1d_idx'), models.Index(fields=['tenant', 'is_active'], name='accounts_te_tenant__6c4fdd_idx')],
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
