# Generated by Django 5.1.15 on 2026-07-16 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import hashlib


def backfill_security_state(apps, schema_editor):
    Invitation = apps.get_model("accounts", "TenantInvitation")
    for invitation in Invitation.objects.all().iterator():
        invitation.token_hash = hashlib.sha256(invitation.token.encode()).hexdigest()
        invitation.save(update_fields=["token_hash"])


def backfill_membership_status(apps, schema_editor):
    Membership = apps.get_model("accounts", "TenantMembership")
    Membership.objects.filter(is_active=True).update(status="active")
    Membership.objects.filter(is_active=False).update(status="removed")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverification'),
        ('tenants', '0003_tenant_default_tax_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tenantinvitation',
            name='accounts_te_token_c89c80_idx',
        ),
        migrations.AddField(
            model_name='tenantinvitation',
            name='token_hash',
            field=models.CharField(editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.RunPython(backfill_security_state, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='tenantinvitation',
            name='token',
        ),
        migrations.AlterField(
            model_name='tenantinvitation',
            name='token_hash',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='tenantinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships_invited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended'), ('removed', 'Removed')], default='active', max_length=16),
        ),
        migrations.RunPython(backfill_membership_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tenantinvitation',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('cashier', 'Cashier'), ('admin', 'Admin'), ('viewer', 'Viewer')], max_length=32),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('owner_admin', 'Owner/Admin'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('viewer', 'Viewer')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['token_hash'], name='accounts_te_token_h_13bdd1_idx'),
        ),
    ]
