# Generated by Django 5.1.15 on 2026-07-01 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('purchase_created', 'Purchase created'), ('purchase_updated', 'Purchase updated'), ('purchase_duplicated', 'Purchase duplicated'), ('purchase_received', 'Purchase received'), ('purchase_cancelled', 'Purchase cancelled'), ('stock_adjustment_created', 'Stock adjustment created'), ('stock_adjustment_updated', 'Stock adjustment updated'), ('stock_adjustment_posted', 'Stock adjustment posted'), ('stock_adjustment_cancelled', 'Stock adjustment cancelled'), ('role_assigned', 'Role assigned'), ('role_updated', 'Role updated')], max_length=64)),
                ('target_object_id', models.CharField(max_length=64)),
                ('target_label', models.CharField(max_length=255)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'action'], name='audit_audit_tenant__3e5f7e_idx'), models.Index(fields=['tenant', 'target_content_type', 'target_object_id'], name='audit_audit_tenant__7dd317_idx'), models.Index(fields=['tenant', 'created_at'], name='audit_audit_tenant__290b62_idx')],
            },
        ),
    ]
