# Generated by Django 5.1.15 on 2026-07-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('purchase_created', 'Purchase created'), ('purchase_updated', 'Purchase updated'), ('purchase_duplicated', 'Purchase duplicated'), ('purchase_received', 'Purchase received'), ('purchase_cancelled', 'Purchase cancelled'), ('stock_adjustment_created', 'Stock adjustment created'), ('stock_adjustment_updated', 'Stock adjustment updated'), ('stock_adjustment_posted', 'Stock adjustment posted'), ('stock_adjustment_cancelled', 'Stock adjustment cancelled'), ('role_assigned', 'Role assigned'), ('role_updated', 'Role updated'), ('invitation_created', 'Invitation created'), ('invitation_accepted', 'Invitation accepted'), ('invitation_revoked', 'Invitation revoked'), ('member_suspended', 'Member suspended'), ('member_removed', 'Member removed'), ('workspace_switched', 'Workspace switched')], max_length=64),
        ),
    ]
