# Generated by Django 5.1.15 on 2026-06-30 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_number', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('order_date', models.DateField()),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases_created', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases_received', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='suppliers.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='catalog.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='purchasing.purchase')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['tenant', 'purchase_number'], name='purchasing__tenant__a62c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['tenant', 'supplier'], name='purchasing__tenant__1fde15_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['tenant', 'status'], name='purchasing__tenant__6678d2_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['tenant', 'order_date'], name='purchasing__tenant__071bea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('tenant', 'purchase_number')},
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['tenant', 'purchase'], name='purchasing__tenant__3d14b6_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['tenant', 'product'], name='purchasing__tenant__a0a4ae_idx'),
        ),
    ]
